server:
  port: 8040
spring:
  application:
    name: jackhe-cloud-zuul-gateway
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/   
      #defaultZone: http://localhost:8030/eureka/,http://localhost:8031/eureka/  #多个EurekaServer注册中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
zuul:                                               #默认是代理所有的EurekaServer注册的微服务
  ignored-services: '*'      #忽略掉jackhe-cloud-user-service的EurekaServer的微服务代理  如果是'*'则是忽略所有微服务，只会代理指定的路由
  #ignoredPatterns: /**/admin/**                    #忽略所有包含/admin/的路径 映射到路由中包含admin的也会忽略掉
  prefix: /jackhe                                   #给所有路由增加前缀/jackhe/user/** 相当于/jackhe-cloud-user-service/**的访问
  #strip-prefix: false                              #在转发请求之前，从请求中删除代理前缀（使用zuul.stripPrefix = false关闭此行为）。prefix和stripPrefix(依赖于prefix的使用)连用影响是全局的 该属性存在一定的问题（不推荐使用）
  routes:                                           #指定微服务的serviceId=指定路径 
    jackhe-cloud-user-service: /user/**
    jackhe-cloud-consumer-service: /consumer/**
logging:
  level:
    com.netflix: DEBUG                              #查看路由调用日志打印

# 上传大文件得将超时时间设置长一些，否则会报超时异常。以下几行超时设置来自http://cloud.spring.io/spring-cloud-static/Camden.SR3/#_uploading_files_through_zuul
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000