server:
  port: 8021
spring:
  application:
    name: jackhe-cloud-consumer-service
  rabbitmq:                              #rabbitmq消息队列监控
    host: localhost
    port: 5672
    username: guest
    password: guest
  level:
    root: INFO
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/
      #defaultZone: http://localhost:8030/eureka/,http://localhost:8031/eureka/  #多个EurekaServer注册中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    leaseRenewalIntervalInSeconds: 1                #注册服务心跳时间1s 默认心跳时间为30秒
    leaseExpirationDurationInSeconds: 2             #等待下一次心跳的超时时间2s  默认为90秒
#feign:
#  hystrix:
#    enabled: true  # 是否启用熔断器整个微服务启用
