server:
  port: 8020
spring:
  application:
    name: jackhe-cloud-consumer-service
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/
      #defaultZone: http://localhost:8030/eureka/,http://localhost:8031/eureka/  #多个EurekaServer注册中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#feign:
#  hystrix:
#    enabled: false  # 是否禁止熔断器整个微服务禁用