server:
  port: 8060
spring:
  application:
    name: jackhe-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/mufengluoyu/jackhe-config      # 配置Git仓库的地址
          username:                                                         # Git仓库的账号
          password:                                                         # Git仓库的密码
          #search-paths: jack-cloud-base                                    # 仓库下面的额文件夹
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8030/eureka/     #
      #defaultZone: http://localhost:8030/eureka/,http://localhost:8031/eureka/  #多个EurekaServer注册中心
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}